INSERT INTO users (name, age) VALUES ("Katie", 30);
INSERT INTO users (name, age) VALUES ("Katie", 30);
INSERT INTO users (name, age) VALUES ("Katie", 30);
INSERT INTO users (name, age) VALUES ("Katie", 30);
INSERT INTO users (name, age) VALUES ("Katie", 30);
INSERT INTO users (name, age) VALUES ("Katie", 30);
INSERT INTO users (name, age) VALUES ("Katie", 30);
INSERT INTO users (name, age) VALUES ("Katie", 30);
INSERT INTO users (name, age) VALUES ("Katie", 30);
INSERT INTO users (name, age) VALUES ("Katie", 30);
INSERT INTO users (name, age) VALUES ("Katie", 30);
INSERT INTO users (name, age) VALUES ("Katie", 30);
INSERT INTO users (name, age) VALUES ("Katie", 30);
INSERT INTO users (name, age) VALUES ("Katie", 30);
INSERT INTO users (name, age) VALUES ("Katie", 30);
INSERT INTO users (name, age) VALUES ("Katie", 30);
INSERT INTO users (name, age) VALUES ("Katie", 30);
INSERT INTO users (name, age) VALUES ("Katie", 30);
INSERT INTO users (name, age) VALUES ("Katie", 30);
INSERT INTO users (name, age) VALUES ("Katie", 30);


INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100, "01-01-19", "01-31-19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100, "01-01-19", "01-31-19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100, "01-01-19", "01-31-19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100, "01-01-19", "01-31-19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100, "01-01-19", "01-31-19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100, "01-01-19", "01-31-19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100, "01-01-19", "01-31-19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100, "01-01-19", "01-31-19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100, "01-01-19", "01-31-19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("title", "category", 100, "01-01-19", "01-31-19");

INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 1, 1);
